version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"